# The ID of the item. List: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
item-id: RECOVERY_COMPASS

# The slot number where the item will be placed in the player's inventory.
# 0 is the first slot, 8 is the last hotbar slot.
item-slot: 4

# The name of the item. Supports standard (&) and HEX (<#RRGGBB>) color codes.
item-name: "<#8a7d93>Server Selector"

# The lore of the item. Supports standard (&) and HEX (<#RRGGBB>) color codes.
item-lore:
  - "&7Click to open the menu."

# CustomModelData for the item. Requires a resource pack on the client.
# Set to 0 to disable.
custom-model-data: 0

# The sound that plays on click. List: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
sound: "BLOCK_AMETHYST_BLOCK_PLACE"

# --- COMMAND TO EXECUTE ---
# Should a command be executed when the player interacts with the item?
command_enabled: true
# The command to be executed by the player. Supports PlaceholderAPI.
# The leading "/" is not needed.
command: "say Test"